### ISSUE TITLE
All lunar MCP-like remappings:

### ISSUE THREAD

**Issue by ghost** [Decencies/Articles#2]
All lunar MCP-like remappings are in ```.lunarclient\offline\(ver)\patch\v_1_(ver)\mappings.txt``` and the same goes for the patches which are in ```.lunarclient\offline\(ver)\patch\v_1_(ver)\patches.txt``` if this helps anything.

**Comment by Decencies** [comment]
This is correct.
I have not really had the time to re-write the patcher section, although I might make a start today.
