### ISSUE TITLE
I want to make lunar work on cracked minecraft

### ISSUE THREAD

**Issue by HorrorBest** [Decencies/Articles#3]
I tried to decompile Lunar client files to see if I can remove that and get lunar to lunch me straight to Multiplayer with a name from my launcher but I failed. and I thought if you could help

**Comment by Decencies** [comment]
you would have to write a patcher which would use all of the patch files within the `lunar-prod` jar, then you would call the `net.minecraft.client.main.Main` class with the game's inital startup parameters, containing your custom session credentials.
As for automatically joining a server, you must specify the `server` option with the server you would like to join upon launching.
